package com.igoy86.nexttranslate.data.local.entity;

import androidx.annotation.NonNull;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * Room database entity representing a single user-created collection.
 *
 * <p>This class maps directly to the {@code collections} table in the Room
 * database. It belongs to the data layer and should never be exposed directly
 * to the domain or presentation layers. Use
 * {@link com.igoy86.nexttranslate.data.mapper.CollectionMapper} to convert
 * between this entity and the domain model
 * {@link com.igoy86.nexttranslate.domain.model.CollectionItem}.</p>
 *
 * <p>Table schema:</p>
 * <pre>
 *     TABLE collections (
 *         id          INTEGER PRIMARY KEY AUTOINCREMENT,
 *         name        TEXT NOT NULL,
 *         color_hex   TEXT NOT NULL,
 *         created_at  INTEGER NOT NULL
 *     )
 * </pre>
 */
@Entity(tableName = "collections")
public class CollectionEntity {

    /**
     * The unique identifier for this collection.
     * Auto-generated by Room on insertion.
     */
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    private long id;

    /**
     * The display name of this collection (e.g. "Travel", "Work").
     * Stored as a non-null TEXT column.
     */
    @NonNull
    @ColumnInfo(name = "name")
    private String name;

    /**
     * The accent color for this collection stored as a hex string
     * (e.g. "#FF5252", "#448AFF"). Used for the card color in the grid.
     * Stored as a non-null TEXT column.
     */
    @NonNull
    @ColumnInfo(name = "color_hex")
    private String colorHex;

    /**
     * The Unix timestamp in milliseconds when this collection was created.
     * Used for sorting collections from newest to oldest.
     */
    @ColumnInfo(name = "created_at")
    private long createdAt;

    // -------------------------------------------------------------------------
    // Constructor
    // -------------------------------------------------------------------------

    /**
     * Constructs a new {@link CollectionEntity} with all required fields.
     *
     * @param name      the display name of the collection; must not be null
     * @param colorHex  the accent color in hex format (e.g. "#FF5252"); must not be null
     * @param createdAt the Unix timestamp in milliseconds when created
     */
    public CollectionEntity(
            @NonNull String name,
            @NonNull String colorHex,
            long createdAt
    ) {
        this.name = name;
        this.colorHex = colorHex;
        this.createdAt = createdAt;
    }

    // -------------------------------------------------------------------------
    // Getters and Setters
    // -------------------------------------------------------------------------

    /**
     * Returns the unique database identifier for this collection.
     *
     * @return the auto-generated database ID
     */
    public long getId() { return id; }

    /**
     * Sets the unique database identifier for this collection.
     * Called automatically by Room after insertion.
     *
     * @param id the database ID assigned by Room
     */
    public void setId(long id) { this.id = id; }

    /**
     * Returns the display name of this collection.
     *
     * @return the collection name; never null
     */
    @NonNull
    public String getName() { return name; }

    /**
     * Sets the display name of this collection.
     *
     * @param name the new name; must not be null
     */
    public void setName(@NonNull String name) { this.name = name; }

    /**
     * Returns the accent color of this collection as a hex string.
     *
     * @return the color hex string (e.g. "#FF5252"); never null
     */
    @NonNull
    public String getColorHex() { return colorHex; }

    /**
     * Sets the accent color of this collection.
     *
     * @param colorHex the new color hex string; must not be null
     */
    public void setColorHex(@NonNull String colorHex) { this.colorHex = colorHex; }

    /**
     * Returns the Unix timestamp in milliseconds when this collection was created.
     *
     * @return the creation timestamp in milliseconds
     */
    public long getCreatedAt() { return createdAt; }

    /**
     * Sets the Unix timestamp in milliseconds when this collection was created.
     *
     * @param createdAt the creation timestamp in milliseconds
     */
    public void setCreatedAt(long createdAt) { this.createdAt = createdAt; }

    // -------------------------------------------------------------------------
    // Object overrides
    // -------------------------------------------------------------------------

    @Override
    public String toString() {
        return "CollectionEntity{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", colorHex='" + colorHex + '\'' +
                ", createdAt=" + createdAt +
                '}';
    }
}
