package com.igoy86.nexttranslate.data.local.entity;

import androidx.annotation.NonNull;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.Index;
import androidx.room.PrimaryKey;

/**
 * Room database entity representing a single word saved inside a user collection.
 *
 * <p>This class maps directly to the {@code collection_words} table in the Room
 * database. It belongs to the data layer and should never be exposed directly to
 * the domain or presentation layers. Use
 * {@link com.igoy86.nexttranslate.data.mapper.CollectionWordMapper} to convert
 * between this entity and the domain model
 * {@link com.igoy86.nexttranslate.domain.model.CollectionWordItem}.</p>
 *
 * <p>A {@link ForeignKey} constraint links each word to its parent
 * {@link CollectionEntity}. When a collection is deleted, all associated words
 * are automatically removed via {@link ForeignKey#CASCADE}.</p>
 *
 * <p>Table schema:</p>
 * <pre>
 *     TABLE collection_words (
 *         id              INTEGER PRIMARY KEY AUTOINCREMENT,
 *         collection_id   INTEGER NOT NULL REFERENCES collections(id) ON DELETE CASCADE,
 *         word            TEXT NOT NULL,
 *         definition      TEXT NOT NULL,
 *         added_at        INTEGER NOT NULL
 *     )
 * </pre>
 */
@Entity(
        tableName = "collection_words",
        foreignKeys = @ForeignKey(
                entity = CollectionEntity.class,
                parentColumns = "id",
                childColumns = "collection_id",
                onDelete = ForeignKey.CASCADE
        ),
        indices = {@Index("collection_id")}
)
public class CollectionWordEntity {

    /**
     * The unique identifier for this word record.
     * Auto-generated by Room on insertion.
     */
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    private long id;

    /**
     * The foreign key referencing the parent {@link CollectionEntity}.
     * Indexed to speed up queries filtering by collection.
     */
    @ColumnInfo(name = "collection_id")
    private long collectionId;

    /**
     * The word or phrase saved by the user.
     * Stored as a non-null TEXT column.
     */
    @NonNull
    @ColumnInfo(name = "word")
    private String word;

    /**
     * A short definition or context for the word.
     * May be sourced from the Dictionary API or the AI explanation endpoint.
     * Stored as a non-null TEXT column.
     */
    @NonNull
    @ColumnInfo(name = "definition")
    private String definition;

    /**
     * Unix timestamp (milliseconds) recording when this word was saved.
     * Used for ordering words from newest to oldest.
     */
    @ColumnInfo(name = "added_at")
    private long addedAt;

    // -------------------------------------------------------------------------
    // Constructor
    // -------------------------------------------------------------------------

    /**
     * Constructs a new {@link CollectionWordEntity}.
     *
     * @param collectionId the ID of the parent collection; must reference an existing collection
     * @param word         the word or phrase to save; must not be null
     * @param definition   a short definition or context string; must not be null
     * @param addedAt      the Unix timestamp in milliseconds when the word was saved
     */
    public CollectionWordEntity(
            long collectionId,
            @NonNull String word,
            @NonNull String definition,
            long addedAt
    ) {
        this.collectionId = collectionId;
        this.word = word;
        this.definition = definition;
        this.addedAt = addedAt;
    }

    // -------------------------------------------------------------------------
    // Getters and Setters
    // -------------------------------------------------------------------------

    /**
     * Returns the auto-generated primary key of this entity.
     *
     * @return the unique row ID; {@code 0} if the entity has not been inserted yet
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the primary key. Called by Room after insertion.
     *
     * @param id the auto-generated row ID
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Returns the foreign key referencing the parent collection.
     *
     * @return the collection ID this word belongs to
     */
    public long getCollectionId() {
        return collectionId;
    }

    /**
     * Sets the foreign key referencing the parent collection.
     *
     * @param collectionId the parent collection ID
     */
    public void setCollectionId(long collectionId) {
        this.collectionId = collectionId;
    }

    /**
     * Returns the saved word or phrase.
     *
     * @return the word string; never null
     */
    @NonNull
    public String getWord() {
        return word;
    }

    /**
     * Sets the saved word or phrase.
     *
     * @param word the word string; must not be null
     */
    public void setWord(@NonNull String word) {
        this.word = word;
    }

    /**
     * Returns the short definition or context for this word.
     *
     * @return the definition string; never null
     */
    @NonNull
    public String getDefinition() {
        return definition;
    }

    /**
     * Sets the short definition or context for this word.
     *
     * @param definition the definition string; must not be null
     */
    public void setDefinition(@NonNull String definition) {
        this.definition = definition;
    }

    /**
     * Returns the Unix timestamp in milliseconds when this word was saved.
     *
     * @return the timestamp in milliseconds
     */
    public long getAddedAt() {
        return addedAt;
    }

    /**
     * Sets the Unix timestamp when this word was saved.
     *
     * @param addedAt the timestamp in milliseconds
     */
    public void setAddedAt(long addedAt) {
        this.addedAt = addedAt;
    }
}
