package com.igoy86.nexttranslate.data.local.entity;

import androidx.annotation.NonNull;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * Room database entity representing a single favorite translation record.
 *
 * <p>This class maps directly to the {@code favorites} table in the Room database.
 * It belongs to the data layer and should never be exposed directly to the
 * domain or presentation layers. Use {@link com.igoy86.nexttranslate.data.mapper.FavoriteMapper}
 * to convert between this entity and the domain model
 * {@link com.igoy86.nexttranslate.domain.model.FavoriteItem}.</p>
 *
 * <p>Table schema:</p>
 * <pre>
 *     TABLE favorites (
 *         id                  INTEGER PRIMARY KEY AUTOINCREMENT,
 *         source_text         TEXT NOT NULL,
 *         translated_text     TEXT NOT NULL,
 *         source_language     TEXT NOT NULL,
 *         target_language     TEXT NOT NULL,
 *         saved_at            INTEGER NOT NULL
 *     )
 * </pre>
 */
@Entity(tableName = "favorites")
public class FavoriteEntity {

    /**
     * The unique identifier for this favorite record.
     * Auto-generated by Room on insertion.
     */
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    private long id;

    /**
     * The original text submitted for translation.
     * Stored as a non-null TEXT column.
     */
    @NonNull
    @ColumnInfo(name = "source_text")
    private String sourceText;

    /**
     * The translated output text produced by ML Kit Translate.
     * Stored as a non-null TEXT column.
     */
    @NonNull
    @ColumnInfo(name = "translated_text")
    private String translatedText;

    /**
     * The BCP-47 language code of the source language (e.g. "en", "id").
     * Stored as a non-null TEXT column.
     */
    @NonNull
    @ColumnInfo(name = "source_language")
    private String sourceLanguageCode;

    /**
     * The BCP-47 language code of the target language (e.g. "id", "ar").
     * Stored as a non-null TEXT column.
     */
    @NonNull
    @ColumnInfo(name = "target_language")
    private String targetLanguageCode;

    /**
     * The Unix timestamp in milliseconds when this favorite was saved by the user.
     * Stored as an INTEGER column. Used to sort favorites from newest to oldest.
     */
    @ColumnInfo(name = "saved_at")
    private long savedAt;

    // -------------------------------------------------------------------------
    // Constructor
    // -------------------------------------------------------------------------

    /**
     * Constructs a new {@link FavoriteEntity} with all required fields.
     *
     * @param sourceText         the original text that was translated
     * @param translatedText     the output text after translation
     * @param sourceLanguageCode the BCP-47 code of the source language
     * @param targetLanguageCode the BCP-47 code of the target language
     * @param savedAt            the Unix timestamp in milliseconds when
     *                           the favorite was saved by the user
     */
    public FavoriteEntity(
            @NonNull String sourceText,
            @NonNull String translatedText,
            @NonNull String sourceLanguageCode,
            @NonNull String targetLanguageCode,
            long savedAt
    ) {
        this.sourceText = sourceText;
        this.translatedText = translatedText;
        this.sourceLanguageCode = sourceLanguageCode;
        this.targetLanguageCode = targetLanguageCode;
        this.savedAt = savedAt;
    }

    // -------------------------------------------------------------------------
    // Getters and Setters
    // -------------------------------------------------------------------------

    /**
     * Returns the unique database identifier for this favorite record.
     *
     * @return the auto-generated database ID
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the unique database identifier for this favorite record.
     * Called automatically by Room after insertion.
     *
     * @param id the database ID assigned by Room
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Returns the original text that was submitted for translation.
     *
     * @return the source text string
     */
    @NonNull
    public String getSourceText() {
        return sourceText;
    }

    /**
     * Sets the original text that was submitted for translation.
     *
     * @param sourceText the source text string; must not be null
     */
    public void setSourceText(@NonNull String sourceText) {
        this.sourceText = sourceText;
    }

    /**
     * Returns the translated output text produced by ML Kit Translate.
     *
     * @return the translated text string
     */
    @NonNull
    public String getTranslatedText() {
        return translatedText;
    }

    /**
     * Sets the translated output text produced by ML Kit Translate.
     *
     * @param translatedText the translated text string; must not be null
     */
    public void setTranslatedText(@NonNull String translatedText) {
        this.translatedText = translatedText;
    }

    /**
     * Returns the BCP-47 language code of the source language.
     *
     * @return the source language code (e.g. "en", "id")
     */
    @NonNull
    public String getSourceLanguageCode() {
        return sourceLanguageCode;
    }

    /**
     * Sets the BCP-47 language code of the source language.
     *
     * @param sourceLanguageCode the source language code; must not be null
     */
    public void setSourceLanguageCode(@NonNull String sourceLanguageCode) {
        this.sourceLanguageCode = sourceLanguageCode;
    }

    /**
     * Returns the BCP-47 language code of the target language.
     *
     * @return the target language code (e.g. "id", "ar")
     */
    @NonNull
    public String getTargetLanguageCode() {
        return targetLanguageCode;
    }

    /**
     * Sets the BCP-47 language code of the target language.
     *
     * @param targetLanguageCode the target language code; must not be null
     */
    public void setTargetLanguageCode(@NonNull String targetLanguageCode) {
        this.targetLanguageCode = targetLanguageCode;
    }

    /**
     * Returns the Unix timestamp in milliseconds when this favorite
     * was saved by the user.
     *
     * @return the saved-at timestamp in milliseconds
     */
    public long getSavedAt() {
        return savedAt;
    }

    /**
     * Sets the Unix timestamp in milliseconds when this favorite
     * was saved by the user.
     *
     * @param savedAt the saved-at timestamp in milliseconds
     */
    public void setSavedAt(long savedAt) {
        this.savedAt = savedAt;
    }

    // -------------------------------------------------------------------------
    // Object overrides
    // -------------------------------------------------------------------------

    /**
     * Returns a string representation of this {@link FavoriteEntity}
     * useful for debugging and logging.
     *
     * @return a formatted string with all fields
     */
    @Override
    public String toString() {
        return "FavoriteEntity{" +
                "id=" + id +
                ", sourceText='" + sourceText + '\'' +
                ", translatedText='" + translatedText + '\'' +
                ", sourceLanguageCode='" + sourceLanguageCode + '\'' +
                ", targetLanguageCode='" + targetLanguageCode + '\'' +
                ", savedAt=" + savedAt +
                '}';
    }
}