package com.igoy86.nexttranslate.domain.model;

import androidx.annotation.NonNull;

/**
 * Domain model representing a single user-created collection.
 *
 * <p>This is a pure Java model class with no Android or framework dependencies,
 * keeping the domain layer clean and testable.</p>
 *
 * <p>A {@link CollectionItem} is a named group that the user creates to
 * organise saved words and translations, similar to Yandex Translate's
 * phrasebook collections. Each collection has a display name, an accent colour
 * used for its card in the grid UI, and a word count reflecting the number
 * of words currently saved inside it.</p>
 *
 * <p>Usage example:</p>
 * <pre>
 *     CollectionItem item = new CollectionItem(
 *         1L, "Travel", "#FF5252", System.currentTimeMillis(), 5
 *     );
 * </pre>
 */
public class CollectionItem {

    /**
     * The unique identifier for this collection.
     * Auto-generated by Room on insertion.
     * A value of {@code 0} indicates the item has not yet been persisted.
     */
    private final long id;

    /**
     * The display name of this collection (e.g. "Travel", "Work", "Slang").
     */
    @NonNull
    private final String name;

    /**
     * The accent color for this collection stored as a hex string
     * (e.g. "#FF5252", "#448AFF"). Used for the card color in the grid UI.
     */
    @NonNull
    private final String colorHex;

    /**
     * The Unix timestamp in milliseconds when this collection was created.
     * Used for sorting collections from newest to oldest.
     */
    private final long createdAt;

    /**
     * The total number of words currently saved inside this collection.
     * Derived from a LEFT JOIN with the {@code collection_words} table
     * at query time. Defaults to {@code 0} for empty collections.
     */
    private final int wordCount;

    // -------------------------------------------------------------------------
    // Constructor
    // -------------------------------------------------------------------------

    /**
     * Constructs a new {@link CollectionItem} with all required fields.
     *
     * @param id        the unique database ID; use {@code 0} for new entries
     * @param name      the display name of the collection; must not be null
     * @param colorHex  the accent color in hex format; must not be null
     * @param createdAt the Unix timestamp in milliseconds when created
     * @param wordCount the number of words saved in this collection; {@code 0} if empty
     */
    public CollectionItem(
            long id,
            @NonNull String name,
            @NonNull String colorHex,
            long createdAt,
            int wordCount
    ) {
        this.id = id;
        this.name = name;
        this.colorHex = colorHex;
        this.createdAt = createdAt;
        this.wordCount = wordCount;
    }

    // -------------------------------------------------------------------------
    // Getters
    // -------------------------------------------------------------------------

    /**
     * Returns the unique database identifier for this collection.
     *
     * @return the database ID, or {@code 0} if not yet persisted
     */
    public long getId() { return id; }

    /**
     * Returns the display name of this collection.
     *
     * @return the collection name; never null
     */
    @NonNull
    public String getName() { return name; }

    /**
     * Returns the accent color of this collection as a hex string.
     *
     * @return the color hex string (e.g. "#FF5252"); never null
     */
    @NonNull
    public String getColorHex() { return colorHex; }

    /**
     * Returns the Unix timestamp in milliseconds when this collection was created.
     *
     * @return the creation timestamp in milliseconds
     */
    public long getCreatedAt() { return createdAt; }

    /**
     * Returns the total number of words saved inside this collection.
     *
     * @return the word count; {@code 0} if the collection is empty
     */
    public int getWordCount() { return wordCount; }

    // -------------------------------------------------------------------------
    // Object overrides
    // -------------------------------------------------------------------------

    @Override
    public String toString() {
        return "CollectionItem{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", colorHex='" + colorHex + '\'' +
                ", createdAt=" + createdAt +
                ", wordCount=" + wordCount +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        CollectionItem that = (CollectionItem) o;
        return id == that.id;
    }

    @Override
    public int hashCode() {
        return Long.valueOf(id).hashCode();
    }
}
