package com.igoy86.nexttranslate.domain.model;

/**
 * Domain model representing a single entry in the user's favorite translations.
 *
 * <p>This is a pure Java model class with no Android or framework dependencies,
 * keeping the domain layer clean and testable.</p>
 *
 * <p>A {@link FavoriteItem} is created when the user explicitly bookmarks a
 * translation result for quick access later. It is persisted to the Room
 * database via the data layer and displayed on the Favorites screen.</p>
 *
 * <p>Unlike {@link HistoryItem}, which is created automatically after every
 * translation, a {@link FavoriteItem} is only created by deliberate user action
 * (tapping the bookmark/favorite button).</p>
 *
 * <p>Usage example:</p>
 * <pre>
 *     FavoriteItem item = new FavoriteItem(
 *         1L,
 *         "Good morning",
 *         "Selamat pagi",
 *         "en",
 *         "id",
 *         System.currentTimeMillis()
 *     );
 * </pre>
 */
public class FavoriteItem {

    /**
     * The unique identifier for this favorite entry.
     * Auto-generated by Room on insertion.
     * A value of {@code 0} indicates the item has not yet been persisted.
     */
    private final long id;

    /**
     * The original text that was submitted for translation.
     */
    private final String sourceText;

    /**
     * The translated output text produced by ML Kit Translate.
     */
    private final String translatedText;

    /**
     * The BCP-47 language code of the source language.
     * Examples: "en" for English, "id" for Indonesian.
     */
    private final String sourceLanguageCode;

    /**
     * The BCP-47 language code of the target language selected by the user.
     * Examples: "id" for Indonesian, "ar" for Arabic.
     */
    private final String targetLanguageCode;

    /**
     * The Unix timestamp in milliseconds when this favorite was saved.
     * Used for sorting favorite entries from newest to oldest.
     */
    private final long savedAt;

    // -------------------------------------------------------------------------
    // Constructor
    // -------------------------------------------------------------------------

    /**
     * Constructs a new {@link FavoriteItem} with all required fields.
     *
     * @param id                 the unique database ID; use {@code 0} for new entries
     * @param sourceText         the original text that was translated
     * @param translatedText     the output text after translation
     * @param sourceLanguageCode the BCP-47 code of the source language (e.g. "en")
     * @param targetLanguageCode the BCP-47 code of the target language (e.g. "id")
     * @param savedAt            the Unix timestamp in milliseconds when the
     *                           favorite was saved by the user
     */
    public FavoriteItem(
            long id,
            String sourceText,
            String translatedText,
            String sourceLanguageCode,
            String targetLanguageCode,
            long savedAt
    ) {
        this.id = id;
        this.sourceText = sourceText;
        this.translatedText = translatedText;
        this.sourceLanguageCode = sourceLanguageCode;
        this.targetLanguageCode = targetLanguageCode;
        this.savedAt = savedAt;
    }

    // -------------------------------------------------------------------------
    // Getters
    // -------------------------------------------------------------------------

    /**
     * Returns the unique database identifier for this favorite entry.
     *
     * @return the database ID, or {@code 0} if not yet persisted
     */
    public long getId() {
        return id;
    }

    /**
     * Returns the original text that was submitted for translation.
     *
     * @return the source text string
     */
    public String getSourceText() {
        return sourceText;
    }

    /**
     * Returns the translated output text produced by ML Kit Translate.
     *
     * @return the translated text string
     */
    public String getTranslatedText() {
        return translatedText;
    }

    /**
     * Returns the BCP-47 language code of the source language.
     *
     * @return the source language code (e.g. "en", "id", "ar")
     */
    public String getSourceLanguageCode() {
        return sourceLanguageCode;
    }

    /**
     * Returns the BCP-47 language code of the target language.
     *
     * @return the target language code (e.g. "en", "id", "ar")
     */
    public String getTargetLanguageCode() {
        return targetLanguageCode;
    }

    /**
     * Returns the Unix timestamp in milliseconds when this favorite
     * was saved by the user.
     *
     * @return the saved-at timestamp in milliseconds
     */
    public long getSavedAt() {
        return savedAt;
    }

    // -------------------------------------------------------------------------
    // Object overrides
    // -------------------------------------------------------------------------

    /**
     * Returns a string representation of this {@link FavoriteItem}
     * useful for debugging and logging.
     *
     * @return a formatted string with all fields
     */
    @Override
    public String toString() {
        return "FavoriteItem{" +
                "id=" + id +
                ", sourceText='" + sourceText + '\'' +
                ", translatedText='" + translatedText + '\'' +
                ", sourceLanguageCode='" + sourceLanguageCode + '\'' +
                ", targetLanguageCode='" + targetLanguageCode + '\'' +
                ", savedAt=" + savedAt +
                '}';
    }

    /**
     * Checks equality based on {@link #id} only, since database IDs
     * are unique identifiers for each favorite entry.
     *
     * @param o the object to compare with
     * @return {@code true} if both objects have the same database ID
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        FavoriteItem that = (FavoriteItem) o;
        return id == that.id;
    }

    /**
     * Returns a hash code based on {@link #id}.
     *
     * @return hash code derived from the database ID
     */
    @Override
    public int hashCode() {
        return Long.valueOf(id).hashCode();
    }
}