package com.igoy86.nexttranslate.domain.model;

/**
 * Domain model representing a single entry in the user's translation history.
 *
 * <p>This is a pure Java model class with no Android or framework dependencies,
 * keeping the domain layer clean and testable.</p>
 *
 * <p>A {@link HistoryItem} is created each time the user performs a translation
 * and is persisted to the Room database via the data layer. It is distinct from
 * {@link TranslationResult}, which represents the immediate output of a
 * translation operation, whereas {@link HistoryItem} is the persisted record
 * stored for later retrieval.</p>
 *
 * <p>Usage example:</p>
 * <pre>
 *     HistoryItem item = new HistoryItem(
 *         1L,
 *         "Hello, world!",
 *         "Halo, dunia!",
 *         "en",
 *         "id",
 *         System.currentTimeMillis()
 *     );
 * </pre>
 */
public class HistoryItem {

    /**
     * The unique identifier for this history entry.
     * Auto-generated by Room on insertion.
     * A value of {@code 0} indicates the item has not yet been persisted.
     */
    private final long id;

    /**
     * The original text that was submitted for translation.
     */
    private final String sourceText;

    /**
     * The translated output text produced by ML Kit Translate.
     */
    private final String translatedText;

    /**
     * The BCP-47 language code of the source language.
     * Examples: "en" for English, "id" for Indonesian.
     */
    private final String sourceLanguageCode;

    /**
     * The BCP-47 language code of the target language selected by the user.
     * Examples: "id" for Indonesian, "ar" for Arabic.
     */
    private final String targetLanguageCode;

    /**
     * The Unix timestamp in milliseconds when this translation was performed.
     * Used for sorting history entries from newest to oldest.
     */
    private final long timestamp;

    // -------------------------------------------------------------------------
    // Constructor
    // -------------------------------------------------------------------------

    /**
     * Constructs a new {@link HistoryItem} with all required fields.
     *
     * @param id                 the unique database ID; use {@code 0} for new entries
     * @param sourceText         the original text that was translated
     * @param translatedText     the output text after translation
     * @param sourceLanguageCode the BCP-47 code of the source language (e.g. "en")
     * @param targetLanguageCode the BCP-47 code of the target language (e.g. "id")
     * @param timestamp          the Unix timestamp in milliseconds when the
     *                           translation was performed
     */
    public HistoryItem(
            long id,
            String sourceText,
            String translatedText,
            String sourceLanguageCode,
            String targetLanguageCode,
            long timestamp
    ) {
        this.id = id;
        this.sourceText = sourceText;
        this.translatedText = translatedText;
        this.sourceLanguageCode = sourceLanguageCode;
        this.targetLanguageCode = targetLanguageCode;
        this.timestamp = timestamp;
    }

    // -------------------------------------------------------------------------
    // Getters
    // -------------------------------------------------------------------------

    /**
     * Returns the unique database identifier for this history entry.
     *
     * @return the database ID, or {@code 0} if not yet persisted
     */
    public long getId() {
        return id;
    }

    /**
     * Returns the original text that was submitted for translation.
     *
     * @return the source text string
     */
    public String getSourceText() {
        return sourceText;
    }

    /**
     * Returns the translated output text produced by ML Kit Translate.
     *
     * @return the translated text string
     */
    public String getTranslatedText() {
        return translatedText;
    }

    /**
     * Returns the BCP-47 language code of the source language.
     *
     * @return the source language code (e.g. "en", "id", "ar")
     */
    public String getSourceLanguageCode() {
        return sourceLanguageCode;
    }

    /**
     * Returns the BCP-47 language code of the target language.
     *
     * @return the target language code (e.g. "en", "id", "ar")
     */
    public String getTargetLanguageCode() {
        return targetLanguageCode;
    }

    /**
     * Returns the Unix timestamp in milliseconds when this translation
     * was performed.
     *
     * @return the timestamp in milliseconds
     */
    public long getTimestamp() {
        return timestamp;
    }

    // -------------------------------------------------------------------------
    // Object overrides
    // -------------------------------------------------------------------------

    /**
     * Returns a string representation of this {@link HistoryItem}
     * useful for debugging and logging.
     *
     * @return a formatted string with all fields
     */
    @Override
    public String toString() {
        return "HistoryItem{" +
                "id=" + id +
                ", sourceText='" + sourceText + '\'' +
                ", translatedText='" + translatedText + '\'' +
                ", sourceLanguageCode='" + sourceLanguageCode + '\'' +
                ", targetLanguageCode='" + targetLanguageCode + '\'' +
                ", timestamp=" + timestamp +
                '}';
    }

    /**
     * Checks equality based on {@link #id} only, since database IDs
     * are unique identifiers for each history entry.
     *
     * @param o the object to compare with
     * @return {@code true} if both objects have the same database ID
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        HistoryItem that = (HistoryItem) o;
        return id == that.id;
    }

    /**
     * Returns a hash code based on {@link #id}.
     *
     * @return hash code derived from the database ID
     */
    @Override
    public int hashCode() {
        return Long.valueOf(id).hashCode();
    }
}